nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
telefone = input("Digite seu telefone: ")
email = input("Digite seu e-mail: ")

print("\nInformações cadastradas:")
print("Nome:", nome)
print("Idade:", idade)
print("Telefone:", telefone)
print("E-mail:", email)